# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='file_zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('fileName', models.FileField(upload_to='./upload/')),
            ],
        ),
    ]
